export const GROCERY_CATEGORIES = [
  "Fresh Vegetables",
  "Fresh Fruits",
  "Dairy & Breakfast",
  "Rice, Atta & Grains",
  "Pulses & Dals",
  "Oils & Ghee",
  "Masalas & Spices",
  "Snacks & Namkeen",
  "Biscuits & Cookies",
  "Chocolates & Sweets",
  "Tea & Coffee",
  "Soft Drinks & Juices",
  "Energy Drinks",
  "Bakery & Cakes",
  "Frozen Foods",
  "Instant Foods",
  "Noodles & Pasta",
  "Ready-to-Cook Foods",
  "Dry Fruits & Nuts",
  "Pickles & Sauces",
  "Organic Products",
  "Meat & Seafood",
  "Eggs & Poultry",
  "Personal Care",
  "Skin Care",
  "Hair Care",
  "Oral Care",
  "Baby Care",
  "Pet Care",
  "Household Essentials",
  "Cleaning Supplies",
  "Laundry Products",
  "Kitchen Essentials",
  "Bath & Body",
  "Health & Wellness",
  "Stationery & Office Supplies",
  "Home & Kitchen Appliances",
  "Seasonal Products",
  "Imported Foods",
  "Bakery Ingredients",
  "Cooking Ingredients",
  "Breakfast Cereals",
  "Honey & Spreads",
  "Ice Cream & Desserts",
  "Fresh Flowers",
  "Festive Specials",
  "Combo Offers",
  "Best Sellers",
  "New Arrivals",
  "Daily Essentials"
] as const;
